### ISSUE TITLE
Sha1 is deprecated, use Sha256 instead

### ISSUE THREAD

**Issue by LOZORD** [wjwwood/homebrew-zork#4]
Running `brew upgrade` gives the following warnings:

```
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/jzip.rb:6:in `<class:Jzip>'
Please report this to the wjwwood/zork tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/jzip.rb:6:in `<class:Jzip>'
Please report this to the wjwwood/zork tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/jzip.rb:6:in `<class:Jzip>'
Please report this to the wjwwood/zork tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/zork1.rb:9:in `<class:Zork1>'
Please report this to the wjwwood/zork tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/zork1.rb:9:in `<class:Zork1>'
Please report this to the wjwwood/zork tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/wjwwood/homebrew-zork/zork1.rb:9:in `<class:Zork1>'
Please report this to the wjwwood/zork tap!
```

**Comment by wjwwood** [comment]
Thanks for the report, maybe someone has time for a pr to fix this, I'm pretty busy atm.
